name: community_server
description: Backend server for LearnEase Community Contributions
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  http: ^1.2.0
  dart_jsonwebtoken: ^3.3.1
  bcrypt: ^1.1.3
  uuid: ^4.5.1
  sqlite3: ^2.9.3
  mailer: ^6.0.0
  mongo_dart: ^0.10.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
